### 2.1.5. 节省内存

In [2]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [9]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [13]:
Z = torch.zeros_like(Y)
print(f'Z = {Z}')
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

Z = tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 139794383843480
id(Z): 139794383843480


In [18]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A.shape)
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A)
print(sum_A.shape)

torch.Size([5, 4])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])


### 范数

In [32]:
u = torch.range(1, 4).reshape((2, 2, 1))
print(u)
print(u.shape)
torch.norm(u)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


/home/mkid/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor(5.4772)

### 梯度计算

In [3]:
x = torch.arange(4.0)
x2 = torch.arange(4.0) + 4
x, x2

(tensor([0., 1., 2., 3.]), tensor([4., 5., 6., 7.]))

In [42]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
print(x.grad)  # 默认值是None

None


In [54]:
# y = 2 * x.T * x
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [56]:
y.backward()
x.grad

/home/mkid/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py:156: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811748419/work/c10/cuda/CUDAFunctions.cpp:112.)
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag


tensor([ 0.,  4.,  8., 12.])

In [57]:
print(f'x = {x}, x.grad = {x.grad}')

x = tensor([0., 1., 2., 3.], requires_grad=True), x.grad = tensor([ 0.,  4.,  8., 12.])


In [59]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])